Presentation/SmartStore.Web/Models/Common/AccountDropdownModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class AccountDropdownModel : EntityModelBase
    {
        public string Name { get; set; }
        public bool IsAuthenticated { get; set; }
        public bool DisplayAdminLink { get; set; }
        public bool ShoppingCartEnabled { get; set; }
        public int ShoppingCartItems { get; set; }

        public bool WishlistEnabled { get; set; }
        public int WishlistItems { get; set; }

        public bool AllowPrivateMessages { get; set; }
        public string UnreadPrivateMessages { get; set; }
        public string AlertMessage { get; set; }

        [SmartResourceDisplayName("Account.Login.Fields.Email")]
        [AllowHtml]
        public string Email { get; set; }

        public bool UsernamesEnabled { get; set; }
        [SmartResourceDisplayName("Account.Login.Fields.UserName")]
        [AllowHtml]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.Login.Fields.Password")]
        [AllowHtml]
        public string Password { get; set; }

        [SmartResourceDisplayName("Account.Login.Fields.RememberMe")]
        public bool RememberMe { get; set; }
    }
}

Presentation/SmartStore.Web/Models/Common/AddressModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Web.Mvc;
using FluentValidation.Attributes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Validators.Common;

namespace SmartStore.Web.Models.Common
{
	[Validator(typeof(AddressValidator))]
    public partial class AddressModel : EntityModelBase
    {
        public AddressModel()
        {
            AvailableCountries = new List<SelectListItem>();
            AvailableStates = new List<SelectListItem>();
            AvailableSalutations = new List<SelectListItem>();
        }

        [SmartResourceDisplayName("Address.Fields.Salutation")]
        public string Salutation { get; set; }
        public bool SalutationEnabled { get; set; }

        [SmartResourceDisplayName("Address.Fields.Title")]
        public string Title { get; set; }
        public bool TitleEnabled { get; set; }

        [SmartResourceDisplayName("Address.Fields.FirstName")]
        [AllowHtml]
        public string FirstName { get; set; }

        [SmartResourceDisplayName("Address.Fields.LastName")]
        [AllowHtml]
        public string LastName { get; set; }

        [SmartResourceDisplayName("Address.Fields.Email")]
        [AllowHtml]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }

        [SmartResourceDisplayName("Address.Fields.EmailMatch")]
		[DataType(DataType.EmailAddress)]
		public string EmailMatch { get; set; }
        public bool ValidateEmailAddress { get; set; }

        [SmartResourceDisplayName("Address.Fields.Company")]
        [AllowHtml]
        public string Company { get; set; }
        public bool CompanyEnabled { get; set; }
        public bool CompanyRequired { get; set; }

        [SmartResourceDisplayName("Address.Fields.Country")]
        public int? CountryId { get; set; }

        [SmartResourceDisplayName("Address.Fields.Country")]
        [AllowHtml]
        public string CountryName { get; set; }
        public bool CountryEnabled { get; set; }

        [SmartResourceDisplayName("Address.Fields.StateProvince")]
        public int? StateProvinceId { get; set; }
        public bool StateProvinceEnabled { get; set; }

        [SmartResourceDisplayName("Address.Fields.StateProvince")]
        [AllowHtml]
        public string StateProvinceName { get; set; }

        [SmartResourceDisplayName("Address.Fields.City")]
        [AllowHtml]
        public string City { get; set; }
        public bool CityEnabled { get; set; }
        public bool CityRequired { get; set; }

        [SmartResourceDisplayName("Address.Fields.Address1")]
        [AllowHtml]
        public string Address1 { get; set; }
        public bool StreetAddressEnabled { get; set; }
        public bool StreetAddressRequired { get; set; }

        [SmartResourceDisplayName("Address.Fields.Address2")]
        [AllowHtml]
        public string Address2 { get; set; }
        public bool StreetAddress2Enabled { get; set; }
        public bool StreetAddress2Required { get; set; }

        [SmartResourceDisplayName("Address.Fields.ZipPostalCode")]
        [AllowHtml]
        public string ZipPostalCode { get; set; }
        public bool ZipPostalCodeEnabled { get; set; }
        public bool ZipPostalCodeRequired { get; set; }

        [SmartResourceDisplayName("Address.Fields.PhoneNumber")]
        [AllowHtml]
		[DataType(DataType.PhoneNumber)]
		public string PhoneNumber { get; set; }
        public bool PhoneEnabled { get; set; }
        public bool PhoneRequired { get; set; }

        [SmartResourceDisplayName("Address.Fields.FaxNumber")]
        [AllowHtml]
		[DataType(DataType.PhoneNumber)]
		public string FaxNumber { get; set; }
        public bool FaxEnabled { get; set; }
        public bool FaxRequired { get; set; }

        public IList<SelectListItem> AvailableCountries { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }
        public IList<SelectListItem> AvailableSalutations { get; set; }

		public string FormattedAddress { get; set; }

		public string GetFormattedName()
		{
			var sb = new StringBuilder();

			sb.Append(FirstName);
			if (FirstName.HasValue() && LastName.HasValue())
			{
				sb.Append(" ");
			}
			sb.Append(LastName);

			return sb.ToString();
		}

		public string GetFormattedCityStateZip()
		{
			var sb = new StringBuilder();

			if (CityEnabled && City.HasValue())
			{
				sb.Append(City);
				if ((StateProvinceEnabled && StateProvinceName.HasValue()) || (ZipPostalCodeEnabled && ZipPostalCode.HasValue()))
				{
					sb.Append(", ");
				}
			}

			if (StateProvinceEnabled && StateProvinceName.HasValue())
			{
				sb.Append(StateProvinceName);
				if (ZipPostalCodeEnabled && ZipPostalCode.HasValue())
				{
					sb.Append(" ");
				}
			}

			if (ZipPostalCodeEnabled && ZipPostalCode.HasValue())
			{
				sb.Append(ZipPostalCode);
			}

			return sb.ToString();
		}
	}
}

Presentation/SmartStore.Web/Models/Common/CompareDropdownModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class CompareDropdownModel : EntityModelBase
    {
        public string Name { get; set; }
    }
}

Presentation/SmartStore.Web/Models/Common/CurrencyModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class CurrencyModel : EntityModelBase
    {
        public string Name { get; set; }
        public string ISOCode { get; set; }
        public string Symbol { get; set; }
    }
}

Presentation/SmartStore.Web/Models/Common/CurrencySelectorModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class CurrencySelectorModel : ModelBase
    {
        public CurrencySelectorModel()
        {
            AvailableCurrencies = new List<CurrencyModel>();
        }

        public IList<CurrencyModel> AvailableCurrencies { get; set; }

        public int CurrentCurrencyId { get; set; }
    }
}

Presentation/SmartStore.Web/Models/Common/ShopLogoModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Common
{
    public partial class FaviconModel : ModelBase
    {
        public bool Uploaded { get; set; }
        public string FaviconUrl { get; set; }
    }
}

Presentation/SmartStore.Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using SmartStore.Core.Domain;
using SmartStore.Core.Domain.Blogs;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Common;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Forums;
using SmartStore.Core.Domain.Localization;
using SmartStore.Core.Domain.Media;
using SmartStore.Core.Domain.Messages;
using SmartStore.Core.Domain.News;
using SmartStore.Core.Domain.Orders;
using SmartStore.Core.Domain.Security;
using SmartStore.Core.Domain.Seo;
using SmartStore.Core.Domain.Tax;
using SmartStore.Core.Domain.Themes;
using SmartStore.Core.Infrastructure;
using SmartStore.Core.Localization;
using SmartStore.Core.Themes;
using SmartStore.Services;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Customers;
using SmartStore.Services.Directory;
using SmartStore.Services.Forums;
using SmartStore.Services.Localization;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Services.Security;
using SmartStore.Services.Seo;
using SmartStore.Services.Topics;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Pdf;
using SmartStore.Web.Framework.Theming;
using SmartStore.Web.Framework.UI;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Controllers
{
	public partial class CommonController : PublicControllerBase
    {
		private readonly static string[] s_hints = new string[] { "Shopsystem", "Onlineshop Software", "Shopsoftware", "E-Commerce Solution" };

		private readonly ICommonServices _services;
		private readonly ITopicService _topicService;
        private readonly Lazy<ILanguageService> _languageService;
        private readonly Lazy<ICurrencyService> _currencyService;
        private readonly IThemeContext _themeContext;
        private readonly Lazy<IThemeRegistry> _themeRegistry;
        private readonly Lazy<IForumService> _forumservice;
        private readonly Lazy<IGenericAttributeService> _genericAttributeService;
		private readonly Lazy<ICompareProductsService> _compareProductsService;
		private readonly Lazy<IUrlRecordService> _urlRecordService;

		private readonly StoreInformationSettings _storeInfoSettings;
		private readonly CustomerSettings _customerSettings;
        private readonly TaxSettings _taxSettings;
        private readonly CatalogSettings _catalogSettings;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly ThemeSettings _themeSettings;
        private readonly CommonSettings _commonSettings;
		private readonly NewsSettings _newsSettings;
        private readonly BlogSettings _blogSettings;
        private readonly ForumSettings _forumSettings;
        private readonly LocalizationSettings _localizationSettings;
		private readonly Lazy<SecuritySettings> _securitySettings;
		private readonly Lazy<SocialSettings> _socialSettings;
		private readonly Lazy<MediaSettings> _mediaSettings;
		private readonly IOrderTotalCalculationService _orderTotalCalculationService;
		
        private readonly IPriceFormatter _priceFormatter;
		private readonly IPageAssetsBuilder _pageAssetsBuilder;
		private readonly Lazy<IPictureService> _pictureService;
		private readonly Lazy<IManufacturerService> _manufacturerService;
		private readonly Lazy<IProductService> _productService;
        private readonly Lazy<IShoppingCartService> _shoppingCartService;

		private readonly IBreadcrumb _breadcrumb;

		public CommonController(
			ICommonServices services,
			ITopicService topicService,
            Lazy<ILanguageService> languageService,
            Lazy<ICurrencyService> currencyService,
			IThemeContext themeContext,
            Lazy<IThemeRegistry> themeRegistry, 
			Lazy<IForumService> forumService,
            Lazy<IGenericAttributeService> genericAttributeService, 
			Lazy<IMobileDeviceHelper> mobileDeviceHelper,
			Lazy<ICompareProductsService> compareProductsService,
			Lazy<IUrlRecordService> urlRecordService,
			StoreInformationSettings storeInfoSettings,
            CustomerSettings customerSettings, 
            TaxSettings taxSettings, 
			CatalogSettings catalogSettings,
            ShoppingCartSettings shoppingCartSettings,
            EmailAccountSettings emailAccountSettings,
            CommonSettings commonSettings, 
			NewsSettings newsSettings,
			BlogSettings blogSettings, 
			ForumSettings forumSettings,
            LocalizationSettings localizationSettings, 
			Lazy<SecuritySettings> securitySettings,
			Lazy<SocialSettings> socialSettings,
			Lazy<MediaSettings> mediaSettings,
			IOrderTotalCalculationService orderTotalCalculationService, 
			IPriceFormatter priceFormatter,
            ThemeSettings themeSettings, 
			IPageAssetsBuilder pageAssetsBuilder,
			Lazy<IPictureService> pictureService,
			Lazy<IManufacturerService> manufacturerService,
			Lazy<IProductService> productService,
            Lazy<IShoppingCartService> shoppingCartService,
			IBreadcrumb breadcrumb)
        {
			_services = services;
			_topicService = topicService;
            _languageService = languageService;
            _currencyService = currencyService;
            _themeContext = themeContext;
            _themeRegistry = themeRegistry;
            _forumservice = forumService;
            _genericAttributeService = genericAttributeService;
			_compareProductsService = compareProductsService;
			_urlRecordService = urlRecordService;

			_storeInfoSettings = storeInfoSettings;
			_customerSettings = customerSettings;
            _taxSettings = taxSettings;
            _catalogSettings = catalogSettings;
            _shoppingCartSettings = shoppingCartSettings;
            _commonSettings = commonSettings;
			_newsSettings = newsSettings;
            _blogSettings = blogSettings;
            _forumSettings = forumSettings;
            _localizationSettings = localizationSettings;
			_securitySettings = securitySettings;
			_socialSettings = socialSettings;
			_mediaSettings = mediaSettings;

            _orderTotalCalculationService = orderTotalCalculationService;
            _priceFormatter = priceFormatter;

            _themeSettings = themeSettings;
			_pageAssetsBuilder = pageAssetsBuilder;
			_pictureService = pictureService;
			_manufacturerService = manufacturerService;
			_productService = productService;
            _shoppingCartService = shoppingCartService;

			_breadcrumb = breadcrumb;
        }

        #region Utilities

        [NonAction]
        protected LanguageSelectorModel PrepareLanguageSelectorModel()
        {
			var availableLanguages = _services.Cache.Get(string.Format(ModelCacheEventConsumer.AVAILABLE_LANGUAGES_MODEL_KEY, _services.StoreContext.CurrentStore.Id), () =>
            {
                var result = _languageService.Value
					.GetAllLanguages(storeId: _services.StoreContext.CurrentStore.Id)
                    .Select(x => new LanguageModel
                    {
                        Id = x.Id,
                        Name = x.Name,
                        NativeName = LocalizationHelper.GetLanguageNativeName(x.LanguageCulture) ?? x.Name,
                        ISOCode = x.LanguageCulture,
                        SeoCode = x.UniqueSeoCode,
                        FlagImageFileName = x.FlagImageFileName
                    })
                    .ToList();
                return result;
            });

			var workingLanguage = _services.WorkContext.WorkingLanguage;

            var model = new LanguageSelectorModel
            {
                CurrentLanguageId = workingLanguage.Id,
                AvailableLanguages = availableLanguages,
                UseImages = _localizationSettings.UseImagesForLanguageSelection
            };

			string defaultSeoCode = _languageService.Value.GetDefaultLanguageSeoCode();

            foreach (var lang in model.AvailableLanguages)
            {
                //var helper = new LocalizedUrlHelper(HttpContext.Request, true);
				var helper = CreateUrlHelperForLanguageSelector(lang, workingLanguage.Id);

				if (_localizationSettings.SeoFriendlyUrlsForLanguagesEnabled)
                {
                    if (lang.SeoCode == defaultSeoCode && (int)(_localizationSettings.DefaultLanguageRedirectBehaviour) > 0)
                    {
                        helper.StripSeoCode();
                    }
                    else
                    {
                        helper.PrependSeoCode(lang.SeoCode, true);
                    }
                }

                model.ReturnUrls[lang.SeoCode] = helper.RelativePath;
            }

            return model;
        }

		private LocalizedUrlHelper CreateUrlHelperForLanguageSelector(LanguageModel model, int currentLanguageId)
		{
			if (currentLanguageId != model.Id)
			{
				var routeValues = this.Request.RequestContext.RouteData.Values;
				var controller = routeValues["controller"].ToString();

				if (!routeValues.TryGetValue(controller + "id", out var val))
				{
					controller = routeValues["action"].ToString();
					routeValues.TryGetValue(controller + "id", out val);
				}

				int entityId = 0;
				if (val != null)
				{
					entityId = val.Convert<int>();
				}

				if (entityId > 0)
				{
					var activeSlug = _urlRecordService.Value.GetActiveSlug(entityId, controller, model.Id);
					if (activeSlug.HasValue())
					{
						var helper = new LocalizedUrlHelper(Request.ApplicationPath, activeSlug, false);
						return helper;
					}
				}
			}

			return new LocalizedUrlHelper(HttpContext.Request, true);
		}

        [NonAction]
        protected CurrencySelectorModel PrepareCurrencySelectorModel()
        {
			var availableCurrencies = _services.Cache.Get(string.Format(ModelCacheEventConsumer.AVAILABLE_CURRENCIES_MODEL_KEY, _services.WorkContext.WorkingLanguage.Id, _services.StoreContext.CurrentStore.Id), () =>

Presentation/SmartStore.Web/Views/Common/Partials/Favicon.cshtml
 @model FaviconModel
@using SmartStore.Web.Models.Common;
@if (Model.Uploaded)
{
    <link rel="shortcut icon" href="@Model.FaviconUrl" />
}

Presentation/SmartStore.Web/Views/Common/Partials/Footer.cshtml
@model FooterModel
@using SmartStore.Web.Models.Common;

@{ 
	var socialLinks = new List<Tuple<string, string>>();
	if (Model.FacebookLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.FacebookLink, "facebook"));
	}

	if (Model.GooglePlusLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.GooglePlusLink, "google-plus"));
	}

	if (Model.TwitterLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.TwitterLink, "twitter"));
	}

	if (Model.PinterestLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.PinterestLink, "pinterest"));
	}

	if (Model.YoutubeLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.YoutubeLink, "youtube"));
	}

	if (Model.InstagramLink.HasValue())
	{
		socialLinks.Add(new Tuple<string, string>(Model.InstagramLink, "instagram"));
	}

	var invserseFooter = GetThemeVariable<bool>("inverse-footer");
}

@{ Html.RenderWidget("footer_top"); }

@if (Model.ShowSocialLinks && socialLinks.Any())
{
	<div class="footer-social-wrapper">
		<div class="container footer-social">
			<div class="row">
				<div class="col text-center">
					@foreach (var link in socialLinks)
					{
						<a href="@link.Item1" target="_blank" class="btn x-btn-@(invserseFooter ? "clear" : "secondary") btn-circle btn-social btn-brand-@link.Item2">
							<i class="fa fa-@link.Item2"></i>
						</a>
					}
				</div>
			</div>
		</div>
	</div>
}

<div class="footer-main-wrapper">
	<div class="container footer-main">
		<div class="row sm-gutters">

			<div class="col-md-3">
				<nav class="footer-links nav-collapsible">
					<h4 class="footer-title nav-toggler collapsed" data-toggle="collapse" data-target="#footer-info" aria-controls="footer-info" aria-expanded="false">@T("Footer.Info")</h4>
					<div class="collapse nav-collapse" id="footer-info">
						<ul class="list-unstyled">

                            @{ Html.RenderWidget("footer_col_1_before"); }

							@if (Model.ManufacturerEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("ManufacturerList")">@T("Manufacturers.List")</a></li>
							}
							@if (Model.RecentlyAddedProductsEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("RecentlyAddedProducts")">@T("Products.NewProducts")</a></li>
							}
							@if (Model.RecentlyViewedProductsEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("RecentlyViewedProducts")">@T("Products.RecentlyViewedProducts")</a></li>
							}
							@if (Model.CompareProductsEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("CompareProducts")">@T("Products.Compare.List")</a></li>
							}

                            @{ Html.RenderWidget("footer_col_1_after"); }

						</ul>
					</div>
				</nav>
			</div>

			<div class="col-md-3">
				<nav class="footer-links nav-collapsible">
					<h4 class="footer-title nav-toggler collapsed" data-toggle="collapse" data-target="#footer-service" aria-controls="footer-service" aria-expanded="false">
                        <span class="d-none d-md-block">@T("Footer.Service")</span>
                        <span class="d-md-none">@T("Footer.Service.Mobile")</span>
                    </h4>
					<div class="collapse nav-collapse" id="footer-service">
						<ul class="list-unstyled">

                            @{ Html.RenderWidget("footer_col_2_before"); }

							@if (Model.TopicPageUrls.ContainsKey("contactus"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["contactus"]">@T("ContactUs")</a></li>
							}
							@if (Model.BlogEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("Blog")">@T("Blog")</a></li>
							}
							@if (Model.ForumEnabled)
							{
								<li><a class="footer-link" href="@Url.RouteUrl("Boards")">@T("Forum.Forums")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("shippinginfo"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["shippinginfo"]">@T("ShippingReturns")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("paymentinfo"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["paymentinfo"]">@T("Paymentinfo")</a></li>
							}

                            @{ Html.RenderWidget("footer_col_2_after"); }

						</ul>
					</div>
				</nav>
			</div>

			<div class="col-md-3">
				<nav class="footer-links company nav-collapsible">
					<h4 class="footer-title nav-toggler collapsed" data-toggle="collapse" data-target="#footer-company" aria-controls="footer-company" aria-expanded="false">
                        <span class="d-none d-md-block">@T("Footer.Company")</span>
                        <span class="d-md-none">@T("Footer.Company.Mobile")</span>
                    </h4>
					<div class="collapse nav-collapse" id="footer-company">
						<ul class="list-unstyled">

                            @{ Html.RenderWidget("footer_col_3_before"); }

							@if (Model.TopicPageUrls.ContainsKey("aboutus"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["aboutus"]">@T("AboutUs")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("imprint"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["imprint"]">@T("Imprint")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("disclaimer"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["disclaimer"]">@T("Disclaimer")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("privacyinfo"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["privacyinfo"]">@T("PrivacyNotice")</a></li>
							}
							@if (Model.TopicPageUrls.ContainsKey("conditionsofuse"))
							{
								<li><a class="footer-link" href="@Model.TopicPageUrls["conditionsofuse"]">@T("ConditionsOfUse")</a></li>
							}

                            @if (Model.DisplayLoginLink)
                            {
                                <li><a class="footer-link" href="@Url.RouteUrl("Login", new { ReturnUrl = Request.RawUrl })">@T("Account.Login")</a></li>
                            }

                            @{ Html.RenderWidget("footer_col_3_after"); }

						</ul>
					</div>
				</nav>
			</div>

			<div class="col-md-3">
				@if (!Model.HideNewsletterBlock)
				{
					<div class="footer-newsletter nav-collapsible" data-subscription-url="@(Url.RouteUrl("SubscribeNewsletter"))">
						<h4 class="footer-title nav-toggler collapsed" data-toggle="collapse" data-target="#footer-newsletter" aria-controls="footer-newsletter" aria-expanded="false">@T("Newsletter.Title")</h4>
						<div class="collapse nav-collapse" id="footer-newsletter">
							<div id="newsletter-subscribe-block">
								<div class="input-group has-icon mb-2">
									@Html.TextBoxFor(x => x.NewsletterEmail, new { id = "newsletter-email", @class = "form-control", placeholder = T("Newsletter.Email") })
									<span class="input-group-icon text-muted">
										<i class="fa fa-envelope"></i>
									</span>
									<div class="input-group-append">
										<button id="newsletter-subscribe-button" class="btn btn-primary btn-icon" title="@T("Newsletter.Button")">
											<i class="fa fa-angle-right"></i>
										</button>
									</div>
								</div>

								<div class="d-none d-lg-block">
									<div class="form-inline">
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="radio" id="newsletter-subscribe" value="newsletter-subscribe" name="optionsRadios" checked="checked">
											<label class="form-check-label" for="newsletter-subscribe">
												<span>@T("Newsletter.Subscribe")</span>
											</label>
										</div>

										<div class="form-check form-check-inline">
											<input class="form-check-input" type="radio" id="newsletter-unsubscribe" value="newsletter-unsubscribe" name="optionsRadios">
											<label class="form-check-label" for="newsletter-unsubscribe">
												<span>@T("Newsletter.Unsubscribe")</span>
											</label>
										</div>
									</div>
								</div>

								@Html.ValidationMessageFor(x => x.NewsletterEmail)

							</div>
							<div id="newsletter-result-block" class="alert alert-success d-none"></div>
						</div>
					</div>
				}

				@if (Model.ShowThemeSelector)
				{
					<div class="theme-selector d-none d-md-block">
						<h4>@T("Footer.Themes")</h4>
						<div class="content">
							@{
								Html.RenderAction("StoreThemeSelector", "Common");
							}
						</div>
					</div>
				}
			</div>
		</div>
	</div>
</div>

@{ Html.RenderWidget("footer_bottom"); }

<div class="footer-bottom-wrapper">
	<div class="container footer-bottom">
		<div class="row sm-gutters">
			<div class="col pb-1 pb-sm-0">
			@if (Model.ShowLegalInfo)
			{
				@Html.Raw(Model.LegalInfo)
			}
			</div>

			@if (Model.SmartStoreHint.HasValue())
			{
				<div class="col-12 col-sm-auto pb-1 pb-sm-0 text-sm-center">
					@Html.Raw(Model.SmartStoreHint)
				</div>
			}

			<div class="col text-sm-right">
				@T("Content.CopyrightNotice", DateTime.Now.Year.ToString(), @Model.StoreName)
			</div>
		</div>
	</div>
</div>